services:
  vendor-portal:
    image: srinidhips/seleniumsuite
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - D:\Automation_Project\docker-workspace\Java-selenium-project\output\vendor-portal:/home/selenium-docker/test-output 
  flight-reservation:
    image: srinidhips/seleniumsuite
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - D:\Automation_Project\docker-workspace\Java-selenium-project\output\flight-reservation:/home/selenium-docker/test-output